<?php
namespace Home\Controller;
use Think\Controller;
class AnchorController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session("userinfo")==null){
            echo "<script>alert('请先登录！')</script>";
            $this->display("Index:index");
        }
    }

    /*
     *获取用户消费记录
     *2016-09-13 sjy
     *
  */
    public function index(){


        $userid  = session('userinfo.userid');
        $webcast = M('webcast');
        $result=$webcast
            ->where(array('userid'=>$userid))
            ->field('createtime,webcastid,videotitle')
            ->select();
        if($result>0){
            $this->assign("lists", $result);
            $this->display("Anchor:income");
        }else{
            $this->error("失败");
        }

    }



    /*
     * 查看房间收益详情 2016-
     * */
    function lookninemoney(){

        $webcastid=$_GET["webcastid"];

        // var_dump($webcastid);

        $usergift = M('usergift');

        $ninemoney=$usergift
            ->where(array('webcastid'=>$webcastid,))
            ->join('wht_userinfos m on m.userid=wht_usergift.frmuserid')
            ->field('wht_usergift.createtime,frmuserid,username,nickname,webcastid,giftprice,giftname')
            ->select();


        $count=0;

        if(count($ninemoney)==0){
            $count=0;
        }else {
            for($i=0;$i<count($ninemoney);$i++){
                $count+=$ninemoney[$i]["giftprice"];
            }
        }



        if($ninemoney>0){

            $this->assign("ninemoney", $count);
            $this->assign("lists", $ninemoney);
            $this->display("Anchor:ninemoney");
        }else{
            $this->error("失败");
        }


    }














}