<?php
namespace Home\Controller;
use Think\Controller;
class ContentController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /*
     * 2016-09-013 视频学堂
     * 直播详细
     * */
    public function index(){
        $id=$_GET["id"];//获取传过来的视频id
        if($id){
            $videoinfo=M("videos")->where(array('nid'=>$id))->find();//得到视频的信息
        }
        if($videoinfo){
        	$where["title|source"]=array('like',array('%'.$videoinfo['source'].'%','%'.$videoinfo['source']),'OR');
        }
        //视频推荐
       	$recommend_video=M('videos')->where($where)->limit(10)->select();
       	//视频排行榜
       	$ranking_video=M('videos')->limit(5)->order('clickcount desc')->select();
       	$this->assign('videoinfo',$videoinfo);
        $this->assign('recommend_video',$recommend_video);
        $this->assign('ranking_video',$ranking_video);
        $this->display();

}
}