<?php
namespace Home\Controller;
use Think\Controller;
use Home\Controller\BaseController;
class IndexController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $title = M('category')->where(array('catid'=>1))->field('title,keywords,description')->find();
        $this->assign('title',$title);
    }

    public function index(){
        $_SESSION["username"]=$_COOKIE["username"];

        $row = M("userinfos")->field("userid,userpwd,username,phone,email,nickname,usergrade,roomid")->where(array("username"=>$_COOKIE["username"]))->find();
        session("userinfo",$row);
        session('userinfo.userpwd',null);
	
	
        //股市频道
        $goldrooms=M("rooms")->where("classifyid=1 and status=1")->limit(0,4)->select();
        //期货频道
        $futures=M("rooms")->where("classifyid=2 and status=1")->limit(0,4)->select();
        //贵金属频道
        $metal=M("rooms")->where("classifyid=3 and status=1")->limit(0,4)->select();
        //精彩视频
        $videos=M("videos")->where("catid=6")->order("clickcount desc")->limit(1,8)->select();
        //大咖秀
        $dakaxiu=M("videos")->where("catid=10")->limit(0,8)->select();

        //视学堂
        $schoolfirst=M("videos")->limit(1)->find();
        //网站标题
        $title=M('category')->where(array('catid'=>1))->find();
        $school=M("videos")->limit(2,8)->select();
        $searchkey=M('searchkey')->order('sort asc')->select();
        $this->assign('searchkey',$searchkey);

        $this->assign("goldrooms",$goldrooms);

        $this->assign("futures",$futures);

        $this->assign("metal",$metal);
        $this->assign("videos",$videos);

        $this->assign("dakaxiu",$dakaxiu);
        $this->assign("title",$title);
        $this->assign("schoolfirst",$schoolfirst);
        $this->assign("school",$school);
        //绑定用户信息
        $this->assign("userinfo",$row);
		$this->display("Index:index");
		
    }

    public function getMore(){
        $this->display("Index:getMore");
    }
	
	public function loginout(){
        setcookie("username",$_SESSION["userinfo.uername"], time()-1, "/", ".9dcj.com");
        session("userinfo",null);
        redirect("http://www.9dcj.com");
    }
	
	/*
     * 2016-09-29 lwx
     * 查询文章详细页
     * */
    public function content(){
        $getid=I('get.id');
        $postnews=M('newsart');
        $where['id']=$getid;
        $content= $postnews->where($where)->find();
        //上一篇
        $front=$postnews->where("id<".$getid)->order('id desc')->limit('1')->find();
        $this->assign('front',$front);
        //下一篇
        $after=$postnews->where("id>".$getid)->order('id desc')->limit('1')->find();
        $where1['recommended']=1;
        $where1['post_status']=1;
        $recommend= $postnews->where($where1)->order('id desc')->limit(10)->select();
        $this->assign("recommend",$recommend);
        $this->assign('after',$after);
        $this->assign('content',$content);
        $this->display();
    }
}