<?php
namespace Home\Controller;
use Think\Controller;
class LiuController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }




    public function liu(){


        $list=M("rooms")
            ->field("roomid,roomtitle,roomnotice,streamname,rdescription")
            ->where('status=1')
            ->select();
        $this->assign("list",$list);
        $this->display("Liu:liu");

    }


//根据传过来的视频流，加载视频
    public function videodetail(){


         $streamname=$_GET["streamname"];
        var_dump($streamname);

        $this->assign("list",$streamname);
        $this->display("Liu:videodetail");
    }


}