<?php
namespace Home\Controller;
use Think\Controller;
header('P3P: CP="CURa ADMa DEVa PSAo PSDo OUR BUS UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR"');
class PersonController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session("userinfo")==null){
            $this->error('请先登录！');
        }
        $userinfo =session("userinfo");//获取个人信息
        $userid=$userinfo["userid"];
        $list  = M("userinfos")->where("userid=$userid")->find();
        $this->assign("list",$list);
    }

    /*
     * 2016-08-26 lwx
     * 个人中心
     * */
    public function index(){

  
        //根据ID获取个人信息
        // p($_SESSION);die;
        $userinfo =session("userinfo");//获取个人信息
        $userid=$userinfo["userid"];//获取个人信息中的userid
        if($userinfo!=null&&$userid>0){
            $list  = M("userinfos")->where("userid=$userid")->find();
            // p($list);die;
            $this->assign("list",$list);

            $this->assign("userinfo",$userinfo);
            //判断当前用户的认证id是否大于0
            if(($list['accredid']>0)||!empty($list['accredid'])){
                //用户提交了个人主播申请认证，查询当前的认证状态并且返回
                $result = M("accred")->where(array("accredid"=>$list['accredid']))->field('status,remark')->find();
                // p($result);die;
                if($result){
                    if($result['status']==1){
                        $mm = "审核通过";
                        $m1 = "已认证";
                        $type = 1;//个人
                        $status =1;
                    }elseif($result['status']==2){
                        $mm = "审核驳回";
                        $m1 = "认证失败";
                        $type = 1;//个人
                        $status =2;
                        // $dd = "<a href={".":U('LiveHall/personedit',array('userid'=>$list['userid']))}>"."重新申请</a>";
                    }else{
                        $mm = "请耐心等待";
                        $m1 = "正在审核中";
                        $type = 1;//个人
                        $status =3;
                    }
                    $result3 = array(
                        "status"=>$m1,
                        "remark"=>$result['remark'],
                        "sm"=>$mm,
                        "type"=>$type,
                        "status1"=>$status,
                        // "zs" => $dd,
                    );
                    $this->assign("accred",$result3);
                }else{
                    $this->assign("istype",1);
                }
            }else{
                //查询用户是否提交的是机构申请
//                var_dump($userid);
//                var_dump($list['accredid']);
                $count = M("applicationforms")->where(array("uid"=>$userid))->field('aid')->count();
                if($count>0){

                    $result1 = M("applicationforms")->where(array("uid"=>$userid))->field('post_status,remark')->find();
//                    var_dump($result1);
                    if($result1['post_status']==1){
                        $mm = "审核通过";
                        $m1 = "已认证";
                        $type = 2;//机构
                        $status =1;
                    }elseif($result1['post_status']==2){
                        $mm = "审核驳回";
                        $m1 = "认证失败";
                        $type = 2;//机构
                        $status =2;
                        // $dd = "<a href={".":U('LiveHall/organizationedit',array('userid'=>$list['userid']))}>"."重新申请</a>";
                    }else{
                        $mm = "请耐心等待";
                        $m1 = "正在审核中";
                        $type = 2;//机构
                        $status =3;
                    }
                    $result2 = array(
                        "status"=>$m1,
                        "remark"=>$result1['remark'],
                        "sm"=>$mm,
                        "type"=>$type,
                        "status1"=>$status,
                        // "zs" => $dd,
                    );
                    if($result1){
                        $this->assign("accred",$result2);
                    }else{
                        $this->assign("istype",1);
                    }
                }else{
                    $this->assign("istype",1);
                }

            }
        }
        $this->display("Person:index");
    }

    /*
     * 2016-08-25 lwx
     * 【登录】用户名（手机号）、邮箱都可登录
     * */
    public function userinfo(){

    }

/*
 * 修改昵称
 * 2016-08-27  sjy
 * */
    public function updatenickname(){
        $userinfo =session("userinfo");//获取个人信息
        $userid=$userinfo["userid"];//获取个人信息中的userid
        $where["userid"]=$userid;
        $nickname=$_POST["username"];
        $result= M('userinfos')
            ->where($where)
            ->setField("nickname",$nickname);
        if($result>0){
            $userinfo["nickname"]=$nickname;
            session("userinfo",$userinfo);
            $this->success("修改成功！",U("Person/index"));
        }else{
            $this->error("失败");
        }
    }


    /*
     * 修改昵称 具体实现
     * 2016-08-27  sjy
     * */
    public function nickname(){
        $userinfo=session("userinfo");
        $userid=$userinfo["userid"];
        $usernick=M("userinfos")->where("userid=$userid")->field("nickname")->find();
        $this->assign("usernick",$usernick["nickname"]);
        $this->display();
    }


    //跳转修改头像的页面
    public function changeIcon(){
        $user=session("userinfo");
        $userid=$user["userid"];
        $where["userid"]=$userid;
        $list  = M("userinfos")->where("userid=$userid")->find();
        $this->assign('list',$list);
        $this->display("Person:changeIcon");
    }



    //修改头像
    public function changeheadImg(){
        // p($_POST);
        // p($_FILES);die;
        $user=session("userinfo");
        $userid=$user["userid"];
        //图片上传到阿里云上
//        $result=$this->upload();
//        $savepath="/Upload/".$user['username'].'/'.$result["upload"]["savename"];
        if(!empty($_FILES['upload']['tmp_name']))
        {
            $setting=C('UPLOAD_SITEIMG_OSS');
            $Upload = new \Think\Upload($setting);
            $info = $Upload->upload($_FILES);
            $imgurl = OSS.$info[upload][savepath].$info[upload][savename];
            $savepath = $imgurl;
        }

        $where["userid"]=$userid;
        // p($savepath);
        // p($result);die;
        // //更改图片
        $res=M("userinfos")->where($where)->setField("headimage",$savepath);
        // p($res);die;
        if($res){
            $this->success("修改成功！",U("Person/index"));
        }else{
            $this->error("修改失败！");
        }
    }

    //跳转充值界面
    public function recharge(){
       $user=session("userinfo");
       $userid=$user["userid"];
       if(!$userid){
            $this->error('请先登录！');die;
       }
////        //生成订单号
////        $ordernum="JDZB".time().$userid;
//        $this->assign("ordernum",$ordernum);
        $this->display("Person:recharge");
    }



    /*
     * 修改密码 2016-09-07 sjy
     * */
    public function updatepwd(){
        $this->display("Person:updatepwd");
}


    /*
    * 修改密码 具体实现 2016-09-07 sjy
    * */

    public function  updatepwdpost(){
            $oldped=$_POST["oldpwd"];

        $pwd=md5($oldped);

            $newpwd=$_POST["newpwd"];
            $renewpwd=$_POST["renewpwd"];
        //判断新密码是否为空
        if(!isset($oldped)||empty($oldped)){
            $this->error("旧密码不能为空");
        }

        //判断旧密码是否为空
        if(!isset($newpwd)||empty($newpwd)){
            $this->error("新密码不能为空");
        }



        $list  = M("userinfos");

        $userinfo =session("userinfo");//获取个人信息
        $userid=$userinfo["userid"];//获取个人信息中的userid

           $re= $list
               ->where("userid=$userid")
               ->field("userpwd")
               ->select();

       if($re[0]["userpwd"]!=$pwd){
           $this->error("原密码不正确");
       }

        if($newpwd!=$renewpwd){
            $this->error("两次密码输入不正确");
        }
        $newpwdmd5=md5($newpwd);
        $data["userpwd"]=$newpwdmd5;
        $update= $list
            ->where("userid=$userid")
            ->data($data)
            ->save();
        if($update){
            $this->success("修改成功！",U("Person/index"));
        }else{
            $this->error("修改失败");
        }



    }

/*
 * 修改个人基本资料 2016-09-07 sjy
 *
 * */

    public function  updateperson(){
        $list  = M("userinfos");

        $userinfo =session("userinfo");//获取个人信息
        $userid=$userinfo["userid"];//获取个人信息中的userid

        $re= $list
            ->where("userid=$userid")
            ->find();
            // p($re);die;
        $this->assign("list",$re);

        $this->display("Person/updateperson");
    }


    public function updatepersonpost(){

        // p($_POST);die;
        // $nickname=$_POST["nickname"];
        // $gender=$_POST["sex"];
        // $qq=$_POST["qq"];
        // $email=$_POST["email"];
        // $weixin=$_POST["weixin"];
        // $birthday=$_POST["birthday"];
        // $job=$_POST["job"];

        // $data["nickname"]=$nickname;
        // $data["gender"]=$gender;
        // $data["qq"]=$qq;
        // $data["email"]=$email;
        // $data["weixin"]=$weixin;
        // $data["job"]=$job;
        // $data["birthday"]=$birthday;
        if (!IS_POST) {
            $this->error('error');die;
        }
        $list  = M("userinfos");

        $userinfo =session("userinfo");//获取个人信息
        $userid=$userinfo["userid"];//获取个人信息中的userid

        $re= $list
            ->where("userid=$userid")
            ->data($_POST)
            ->save();

        if($re>=0){
            $userinfo["nickname"]=$nickname;
            session("userinfo",$userinfo);
            $this->success("修改成功",U('Person/index'));
        }
    }

    public function cpbindphone(){
        $this->display("Person:cpbindphone");
    }

    public function changeemail(){
        $this->display("Person:changeemail");
    }

    public function information(){
        $userinfo =session("userinfo");//获取个人信息
        $this->assign("userinfo",$userinfo);
        $this->display("Person:information");
    }
    public function videourl(){
        $userinfo =session("userinfo");//获取个人信息
        $this->assign("userinfo",$userinfo);


        $userid=$userinfo["userid"];//获取个人信息中的userid
        $lists=M('rooms')
        ->join('wht_userinfos on wht_rooms.roomid=wht_userinfos.roomid')
        ->where(array('wht_userinfos.userid'=>$userid))
        ->field('streamurl,crossfire')
        ->find();
        $this->assign('lists',$lists);
        $this->display();
    }


    // 主播认证
    public function zhubo()
    {
        $userinfo =session("userinfo");//获取个人信息
        $this->assign("userinfo",$userinfo);

        $userinfo=session("");
        $userid = session('userinfo.userid');
		$s = M('applicationforms')->where(array('uid'=>$userid))->field('post_status,remark')->find();
        // p($s);die;
        if ($s[post_status]) {
            $data['status'] = $s[post_status];
			
            $data['name']= '机构申请';
            $data['type'] = 1;
			$data['remark']=$s[remark];
            // p($data);die;
            $this->assign('data',$data);
        }
        $accredid = M('userinfos')->where(array('userid'=>$userid))->getField('accredid');
        $status = M('accred')->where(array('accredid'=>$accredid))->getField('status');

        if ($data1) {
            $data1['name']= '个人申请';
            $data1['status'] = $status;
            // p($data1);die;
            $this->assign('data',$data1);
        }
        $this->display('Person/zhubo');
    }
}