<?php
namespace Home\Controller;
use Think\Controller;
class SubscribeController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session("userinfo")==null){
            echo "<script>alert('请先登录！')</script>";
            $this->display("Index:index");
        }
    }
    public function index(){
           $this->display();

    }

    /*
     * 我的订阅
     * */
    public function subscribe(){
        $user=session("userinfo");

        $this->assign("userinfo",$user);
        $userid=$user["userid"];
        $result=M("userrooms r")
            ->join("wht_rooms m on m.roomid=r.roomid")
            ->field(' m.roomid,r.createtime,m.roomcode,m.headimage,m.webcastkeyid,m.roomtitle')->where("r.userid=$userid")->select();
//             p($result);die;
        $this->assign("userrooms",$result);
        $this->display('Subscribe/subscribe');
    }

    /*
     * 取消关注
     * */
    public function concel()
    {
        $roomid = I('get.roomid');
        $userid = session('userinfo.userid');

        $userrooms = M('userrooms');
        if (!empty($roomid)) {

                $isenable = $userrooms->where(array('roomid'=>$roomid, 'userid'=>$userid))->field('isenable')->find();
                if ($isenable) {

                    $data = $userrooms->where(array('roomid'=>$roomid, 'userid'=>$userid))->delete();
                    if($data) {
                        $this->redirect("Subscribe/subscribe");
                    }else{
                        $this->error("取消异常");
                    }
                }
        }
    }

}