<?php
namespace Home\Controller;
use Think\Controller;
class UserController extends BaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function index(){
        $this->display();
    }

    /*
     * 显示个人信息*/
    public function usermsg(){
        $this->dispaly();
    }

    /*
     * 修改个人信息
     * 所传递的参数需要判断是否为空，为空就不进行修改，否则，就修改
     * 为啥要判断是否为空，怕以前有的字段是有数据的，后来只修改了其中一个，其他的也会被修改成空
     * */
    public function mdyuser(){
        $this->dispaly();
    }
}